Release cycle fixes

diff --git a/.github/workflows/release-cycle.yml b/.github/workflows/release-cycle.yml
--- a/.github/workflows/release-cycle.yml
+++ b/.github/workflows/release-cycle.yml
@@ -23,18 +23,18 @@ jobs:
       - run: bash scripts/git-user-config.sh
       - name: Set changeset status location
         run: |
-          CHANGESETS_STATUS_JSON=$(node --print --eval "require('path').relative(__dirname, '$RUNNER_TEMP/status.json')")
+          CHANGESETS_STATUS_JSON=$(node -p -e "require('path').relative(__dirname, '$RUNNER_TEMP/status.json')")
           echo "CHANGESETS_STATUS_JSON=$CHANGESETS_STATUS_JSON" >> $GITHUB_ENV
       - name: Get changeset status
         run: npx changeset status --output="$CHANGESETS_STATUS_JSON"
       - name: Get new version
         run: |
-          RELEASES=$(node --print --eval "require('$CHANGESETS_STATUS_JSON').releases")
-          if [ $(node --print --eval "$RELEASES.length") != 1 ]; then
+          RELEASES=$(node -p -e "require('$CHANGESETS_STATUS_JSON').releases")
+          if [ $(node -p -e "$RELEASES.length") != 1 ]; then
             echo "::error file=$CHANGESETS_STATUS_JSON::The status doesn't contain only 1 release"
             exit 1;
           fi;
-          NEW_VERSION=$(node --print --eval "($RELEASES)[0].newVersion")
+          NEW_VERSION=$(node -p -e "($RELEASES)[0].newVersion")
           echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
       - name: Open branch
         run: |
@@ -61,7 +61,7 @@ jobs:
           BRANCH_NAME: ${{ github.ref_name }}
         run: |
           BRANCH_VERSION=$(npx semver -c $(echo $BRANCH_NAME | sed "s/release-v//g"))
-          PACKAGE_JSON_NEXT_PATCH=$(npx semver -i $(node --print --eval "require('./package.json').version"))
+          PACKAGE_JSON_NEXT_PATCH=$(npx semver -i $(node -p -e "require('./package.json').version"))
           NEXT_VERSION=$(npx semver $BRANCH_VERSION $PACKAGE_JSON_NEXT_PATCH | tail -n 1)
           echo "TITLE=Release v${NEXT_VERSION}" >> $GITHUB_ENV
       - name: Create PR
@@ -86,7 +86,8 @@ jobs:
       - run: bash scripts/git-user-config.sh
       - name: Exit prerelease state if needed
         run: |
-          if [ -f .changeset/pre.json ]; then
+          PRERELEASE=$(node -p -e 'require("@changesets/pre").readPreState(process.cwd()).then(prestate => console.log(prestate?.mode == "pre"))' | tail -n 1)
+          if [ $PRERELEASE != "false" ]; then
             npx changeset pre exit rc
             git add .
             git commit -m "Exit release candidate"
@@ -106,7 +107,7 @@ jobs:
   publish:
     environment: npm
     name: Promote to final release
-    if: ${{ contains(github.ref_name, 'release-v') && github.event_name == 'push' && steps.changesets.outputs.hasChangesets == 'false' }}
+    if: ${{ contains(github.ref_name, 'release-v') && github.event_name == 'push' }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -115,6 +116,13 @@ jobs:
       - name: Set up environment
         uses: ./.github/actions/setup
       - run: bash scripts/git-user-config.sh
+      - name: Check if ready for publish
+        run: |
+          CHANGESETS_QUANTITY=$(node -p -e "require('@changesets/read').default(process.cwd(), 'main').then(changesets => console.log(changesets.length))" | tail -n 1)
+          if [ $CHANGESETS_QUANTITY != 0 ]; then
+            echo "::error file=$CHANGESETS_STATUS_JSON::The status doesn't contain only 1 release"
+            exit 1;
+          fi;
       - name: Tag
         run: npx changeset tag
       - name: Publish to npm
@@ -123,3 +131,12 @@ jobs:
         run: npm publish
       - name: Upload tags
         run: git push --tags
+      - name: Create Github Release
+        uses: actions/github-script@v6
+        with:
+          script: |
+            github.rest.repos.createRelease({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              tagName: `v${require('./package.json').version}`
+            });
